### PR TITLE
v2.0.0 release

### PR DESCRIPTION
**Pull request by Laul0**

### CODE REVIEW

**Comment by ganigeorgiev** [comment]
@Laul0 Thank you for the PR, but unfortunately Presentator v2 comes with breaking changes and the current docker image need to be updated to use [presentator-starter](https://github.com/ganigeorgiev/presentator-starter) in order to be able to handle updates only by running `composer update`.

I'll try to add Presentator v2 support later today (or by tomorrow at the latest).

**Comment by Laul0** [comment]
Ok, no problem.
I can not wait to see the result 🙂

Thank you for your work 👍🏻

**Comment by ganigeorgiev** [comment]
@Laul0 Just to let you know, I've just pushed the changes to Docker Hub - https://hub.docker.com/r/ganigeorgiev/presentator.

Also make sure to check the [upgrade instructions](https://github.com/presentator/presentator/blob/master/UPGRADE.md) if you are using Presentator v1.

*The v2 images start from `v2.0.4` because I had some issues handling the monorepo tags and I didn't want to rewrite the git history.*

**Comment by Laul0** [comment]
Thx for this information.
I took note about the instruction. I'll make a backup and upgrade it.

**Pull request closed without merging**
